### PR TITLE
Updates on the Documentation

### LINKED ISSUE #39: Email Template
Update: https://sfdo-community-sprints.github.io/summit-events-app-documentation/docs/standard-features/create-event-email/email-templates/
Review/Reference: https://help.salesforce.com/s/articleView?id=sf.admin_emailtemplates.htm&type=5
Intent: 
* Walk through the current process of creating the letter head and email template via the classic process.
* This may be a reference to the standard Salesforce functionality

Note: This is also serving as a placeholder for the future email functionality that'll leverage Lightning Email Templates

### PR DESCRIPTION
**Pull request by ghost**
# Wave 1 on cleaning up the Documentation.

happy-obi-wan

## Updates on the Documentation:

- Cleaned up the Markdown code in the Doc folder in terms of readability.
- Cleaned up the Documentation in terms of grammar, punctuation, spelling, etc.
- Removed the "Email Template" subpage on behalf of @ryannajackson. **Need Permission to close the issue #39**
image
- Edited the readme.md file.

## Questions

1. Under Advanced Features, I notice that "Generated Itinerary" has a dropdown, but nothing is under it. 

DropDown

On the file structure, I noticed that it goes with "Appointments-options" folder.

Folder

Was wonder why this is the case and if it needs to be reordered accordingly.

2. Is there an official folder of images that is Salesforce Approved that can be use in this documentation site? Planning on adding engaging images that are not too distracting, but needed Salesforce approved images.

### Please review since it is a lot. Let me know when to merge this PR!

### CODE REVIEW

**Comment by dwhitig** [comment]
@FrancisTR I think so if @tcdahlberg has no objection.  I deleted the email-template rouge page so I hope that does not cause you issues when you merge.

**Comment by dwhitig** [comment]
@FrancisTR do you know if @tcdahlberg reviewed this?  Wondering if I can mark it as Complete

**Comment by FrancisTR** [comment]
@dwhitig Yep! I talked to @tcdahlberg about this PR when he was in-person. Feel free to mark it as complete!

**Comment by dwhitig** [comment]
Fantastic!

**Pull request merged**
